A try to fix unexpeced failure on build agent that says: 1. /app/dotnet/src/Functions/Functions.OpenApi/Model/RestApiOperation.cs(8,1): warning IDE0005: Using directive is unnecessary. [/app/dotnet/src/Functions/Functions.OpenApi/Functions.OpenApi.csproj]
2. /dotnet/src/Functions/Functions.OpenApi/Model/RestApiOperation.cs(220,50): error CS0103: The name 'SimpleStyleParameterSerializer' does not exist in the current context [/__w/semantic-kernel/semantic-kernel/dotnet/src/Functions/Functions.OpenApi/Functions.OpenApi.csproj]