Python: Azure OpenAI setting fix: Don't fetch AD token if API is present in environment variable. (#8985)
### Motivation and Context

While working on #8951 I found that interacting with an Azure OpenAI
instance I had an API key for, but my identity didn't have IAM access to
the API for, that I was getting a permission error:

```
semantic_kernel.exceptions.service_exceptions.ServiceResponseException: ("<class 'semantic_kernel.connectors.ai.open_ai.services.azure_text_embedding.AzureTextEmbedding'> service failed to generate embeddings", AuthenticationError("Error code: 401 - {'error': {'code': 'PermissionDenied', 'message': 'Principal does not have access to API/Operation.'}}"))
```

I found that this was because, though my API key was set in the
environment, the codepath only recognized an explicitly passed in API
key when deciding whether to issue an AD token while initializing an
AzureTextEmbedding instance.

This PR fixes that by looking at the setting object explicitly, which
may pull the API key from the environment.


### Contribution Checklist

- [x] The code builds clean without any errors or warnings
- [x] The PR follows the [SK Contribution
Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md)
and the [pre-submission formatting
script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts)
raises no violations
- [x] All unit tests pass, and I have added new tests where possible
- [x] I didn't break anyone :smile: