Python: Update Azure Cognitive Search Class Change VectorSearchAlgorithmConfi… (#2435)
…guration to HnswVectorSearchAlgorithmConfiguration

### Motivation and Context

Thank you for your contribution to the semantic-kernel repo!
Please help reviewers and future users, providing the following
information:

  1. Why is this change required?
  
Azure Cognitive Search SDK Change VectorSearchAlgorithmConfiguration to
HwsnVectorSearchAlgorithmConfiguration
  
  2. What problem does it solve?
  
ImportError: cannot import name 'VectorSearchAlgorithmConfiguration'
from 'azure.search.documents.indexes.models'
  
  3. What scenario does it contribute to?

Python SDK Vector DB Change

  5. If it fixes an open issue, please link to the issue here.
  

https://github.com/Azure/cognitive-search-vector-pr/blob/main/demo-python/code/azure-search-vector-python-sample.ipynb

### Description

<!-- Describe your changes, the overall approach, the underlying design.
These notes will help understanding how your code works. Thanks! -->

### Contribution Checklist

<!-- Before submitting this PR, please make sure: -->

- [x] The code builds clean without any errors or warnings
- [x] The PR follows the [SK Contribution
Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md)
and the [pre-submission formatting
script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts)
raises no violations
- [x] All unit tests pass, and I have added new tests where possible
- [x] I didn't break anyone :smile:

---------

Co-authored-by: Lee Miller <lemiller@microsoft.com>