Python: Update README.md (#10028)
prompt_template_config needs PromptTemplateConfig type but req_settings
is PromptExecutionSettings type which seems to be accepted better by
prompt_execution_settings

### Motivation and Context

<!-- Thank you for your contribution to the semantic-kernel repo!
Please help reviewers and future users, providing the following
information:
  1. Why is this change required?
  It throws an error otherwise
  3. What problem does it solve?
AttributeError: 'AzureChatPromptExecutionSettings' object has no
attribute 'execution_settings'
  4. What scenario does it contribute to?
  5. If it fixes an open issue, please link to the issue here.
  It's a README fix :) 

### Description

prompt_template_config needs PromptTemplateConfig type but req_settings
is PromptExecutionSettings type which seems to be accepted better by
prompt_execution_settings

Changed to prompt_execution_settings=req_settings instead of
prompt_template_config=req_settings,

### Contribution Checklist

<!-- Before submitting this PR, please make sure: -->

- [x] The code builds clean without any errors or warnings
- [x] The PR follows the [SK Contribution
Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md)
and the [pre-submission formatting
script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts)
raises no violations
- [x] All unit tests pass, and I have added new tests where possible
- [x] I didn't break anyone :smile: