.Net: Fix CodeQL errors (#10937)
### Motivation and Context

The .Net CodeQL is currently failing and there are a number of errors
and also one warning:

1. Recent prompty related code change: Fixed in this PR
2. Warning with the ChatGptPlugin sample: OpenAI have deprecated plugin
support so I am removing this sample.
3. HuggingFaceImageToText sample requires Windows: I have removed this
sample from the solution so CodeQL will ignore it.

For more details on the errors see: [.Net: Bump DocumentFormat.OpenXml
and System.IO.Packaging in /dotnet … ·
microsoft/semantic-kernel@eb3de69](https://github.com/microsoft/semantic-kernel/actions/runs/13809457343/job/38627467108)
 
```
CSC : warning CS9057: The analyzer assembly '/home/runner/work/semantic-kernel/semantic-kernel/dotnet/samples/Demos/CreateChatGptPlugin/MathPlugin/kernel-functions-generator/bin/Release/netstandard2.0/kernel-functions-generator.dll' references version '4.11.0.0' of the compiler, which is newer than the currently running version '4.8.0.0'. [/home/runner/work/semantic-kernel/semantic-kernel/dotnet/samples/Demos/CreateChatGptPlugin/MathPlugin/azure-function/sk-chatgpt-azure-function.csproj]
[1776](https://github.com/microsoft/semantic-kernel/actions/runs/13809457343/job/38627467108#step:4:1777)  /usr/lib/dotnet/sdk/8.0.112/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(1355,3): error MSB4019: The imported project "/usr/lib/dotnet/sdk/8.0.112/Sdks/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.targets" was not found. Confirm that the expression in the Import declaration ";/usr/lib/dotnet/sdk/8.0.112/Sdks/Microsoft.NET.Sdk/targets/../../Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.targets" is correct, and that the file exists on disk. [/home/runner/work/semantic-kernel/semantic-kernel/dotnet/samples/Demos/HuggingFaceImageToText/HuggingFaceImageToText.csproj]
[1777](https://github.com/microsoft/semantic-kernel/actions/runs/13809457343/job/38627467108#step:4:1778)  /home/runner/work/semantic-kernel/semantic-kernel/dotnet/src/Functions/Functions.Prompty/KernelFunctionPrompty.cs(54,81): error CS1729: 'string' does not contain a constructor that takes 0 arguments [/home/runner/work/semantic-kernel/semantic-kernel/dotnet/src/Functions/Functions.Prompty/Functions.Prompty.csproj::TargetFramework=netstandard2.0]
[1778](https://github.com/microsoft/semantic-kernel/actions/runs/13809457343/job/38627467108#step:4:1779)  /home/runner/work/semantic-kernel/semantic-kernel/dotnet/src/Functions/Functions.Prompty/KernelFunctionPrompty.cs(54,81): error CS1729: 'string' does not contain a constructor that takes 0 arguments [/home/runner/work/semantic-kernel/semantic-kernel/dotnet/src/Functions/Functions.Prompty/Functions.Prompty.csproj::TargetFramework=net8.0]
```

### Description

<!-- Describe your changes, the overall approach, the underlying design.
These notes will help understanding how your code works. Thanks! -->

### Contribution Checklist

<!-- Before submitting this PR, please make sure: -->

- [ ] The code builds clean without any errors or warnings
- [ ] The PR follows the [SK Contribution
Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md)
and the [pre-submission formatting
script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts)
raises no violations
- [ ] All unit tests pass, and I have added new tests where possible
- [ ] I didn't break anyone :smile: